name: Sync to BetterDocs

on:
  push:
    branches:
      - main
    paths:
      - 'SEO/**/*.md'
  workflow_dispatch:

jobs:
  sync-docs:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v40
        with:
          files: 'SEO/**/*.md'

      - name: Sync to BetterDocs
        if: steps.changed-files.outputs.any_changed == 'true'
        env:
          WP_USERNAME: ${{ secrets.WP_USERNAME }}
          WP_APP_PASSWORD: ${{ secrets.WP_APP_PASSWORD }}
          BEARER_TOKEN: ${{ secrets.AIENGINE_BEARER_TOKEN }}
          WP_URL: ${{ secrets.WP_SITE_URL }}
          CATEGORY_ID: ${{ secrets.BETTERDOCS_SEO_CATEGORY_ID }}
          CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          # Convert space-separated list to array
          IFS=' ' read -r -a files <<< "$CHANGED_FILES"
          
          for file in "${files[@]}"; do
            [ -z "$file" ] && continue
            
            echo "Processing: $file"
            
            filename=$(basename "$file" .md)
            title=$(echo "$filename" | sed 's/-/ /g' | sed 's/\b\(.\)/\u\1/g')
            
            content=$(cat "$file")
            
            # Extract front matter if exists
            excerpt=""
            if grep -q "^---$" "$file"; then
              front_matter=$(sed -n '/^---$/,/^---$/p' "$file" | sed '1d;$d')
              
              fm_title=$(echo "$front_matter" | grep -i "^title:" | sed 's/^title: *//I' | sed 's/^["'\'']\(.*\)["'\'']$/\1/')
              if [ ! -z "$fm_title" ]; then
                title="$fm_title"
              fi
              
              excerpt=$(echo "$front_matter" | grep -i "^excerpt:" | sed 's/^excerpt: *//I' | sed 's/^["'\'']\(.*\)["'\'']$/\1/')
              
              content=$(sed '1{/^---$/!q;};1,/^---$/d' "$file")
            fi
            
            auth_header=$(echo -n "$WP_USERNAME:$WP_APP_PASSWORD" | base64)
            
            # Use jq to properly escape JSON
            if [ ! -z "$excerpt" ]; then
              json_payload=$(jq -n \
                --arg title "$title" \
                --arg content "$content" \
                --arg excerpt "$excerpt" \
                --argjson category "$CATEGORY_ID" \
                '{
                  title: $title,
                  content: $content,
                  excerpt: $excerpt,
                  status: "publish",
                  doc_category: [$category]
                }')
            else
              json_payload=$(jq -n \
                --arg title "$title" \
                --arg content "$content" \
                --argjson category "$CATEGORY_ID" \
                '{
                  title: $title,
                  content: $content,
                  status: "publish",
                  doc_category: [$category]
                }')
            fi
            
            echo "Creating/updating post: $title"
            
            response=$(curl -s -w "\n%{http_code}" \
              -X POST \
              -H "Authorization: Basic $auth_header" \
              -H "Content-Type: application/json" \
              -d "$json_payload" \
              "$WP_URL/wp-json/wp/v2/docs")
            
            http_code=$(echo "$response" | tail -n1)
            body=$(echo "$response" | sed '$d')
            
            if [ "$http_code" -eq 200 ] || [ "$http_code" -eq 201 ]; then
              echo "✓ Successfully synced: $title"
              post_id=$(echo "$body" | jq -r '.id')
              echo "Post ID: $post_id"
              echo "URL: $WP_URL/docs/$(echo "$body" | jq -r '.slug')"
              
              # Generate embeddings
              echo "Generating embeddings..."
              embed_payload=$(jq -n --argjson post_id "$post_id" '{postId: $post_id, envId: "default"}')
              
              embed_response=$(curl -s -w "\n%{http_code}" \
                -X POST \
                -H "Authorization: Bearer $BEARER_TOKEN" \
                -H "Content-Type: application/json" \
                -d "$embed_payload" \
                "$WP_URL/wp-json/mwai/v1/vectors/add")
              
              embed_http_code=$(echo "$embed_response" | tail -n1)
              
              if [ "$embed_http_code" -eq 200 ]; then
                echo "✓ Embeddings generated"
              else
                echo "⚠ Embedding generation failed"
              fi
            else
              echo "✗ Failed to sync: $title (HTTP $http_code)"
              echo "$body"
            fi
            
            echo "---"
          done

      - name: Summary
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          echo "Sync completed"
