name: Sync to BetterDocs

on:
  push:
    branches:
      - main
    paths:
      - 'SEO/**/*.md'
  workflow_dispatch:

jobs:
  sync-docs:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v40
        with:
          files: 'SEO/**/*.md'

      - name: Sync to BetterDocs
        if: steps.changed-files.outputs.any_changed == 'true'
        env:
          WP_USERNAME: ${{ secrets.WP_USERNAME }}
          WP_APP_PASSWORD: ${{ secrets.WP_APP_PASSWORD }}
          BEARER_TOKEN: ${{ secrets.AIENGINE_BEARER_TOKEN }}
          WP_URL: ${{ secrets.WP_SITE_URL }}
          CATEGORY_ID: ${{ secrets.BETTERDOCS_SEO_CATEGORY_ID }}
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "Processing: $file"
            
            filename=$(basename "$file" .md)
            title=$(echo "$filename" | sed 's/-/ /g' | sed 's/\b\(.\)/\u\1/g')
            
            content=$(cat "$file")
            
            # Extract front matter if exists
            excerpt=""
            if grep -q "^---$" "$file"; then
              front_matter=$(sed -n '/^---$/,/^---$/p' "$file" | sed '1d;$d')
              
              fm_title=$(echo "$front_matter" | grep -i "^title:" | sed 's/^title: *//I' | sed 's/^["'\'']\(.*\)["'\'']$/\1/')
              if [ ! -z "$fm_title" ]; then
                title="$fm_title"
              fi
              
              excerpt=$(echo "$front_matter" | grep -i "^excerpt:" | sed 's/^excerpt: *//I' | sed 's/^["'\'']\(.*\)["'\'']$/\1/')
              
              content=$(sed '1{/^---$/!q;};1,/^---$/d' "$file")
            fi
            
            auth_header=$(echo -n "$WP_USERNAME:$WP_APP_PASSWORD" | base64)
            
            # Prepare JSON - simpler approach
            if [ ! -z "$excerpt" ]; then
              json_payload="{\"title\":\"$title\",\"content\":\"$content\",\"excerpt\":\"$excerpt\",\"status\":\"publish\",\"doc_category\":[$CATEGORY_ID]}"
            else
              json_payload="{\"title\":\"$title\",\"content\":\"$content\",\"status\":\"publish\",\"doc_category\":[$CATEGORY_ID]}"
            fi
            
            echo "Creating/updating post: $title"
            
            response=$(curl -s -w "\n%{http_code}" \
              -X POST \
              -H "Authorization: Basic $auth_header" \
              -H "Content-Type: application/json" \
              -d "$json_payload" \
              "$WP_URL/wp-json/wp/v2/docs")
            
            http_code=$(echo "$response" | tail -n1)
            body=$(echo "$response" | sed '$d')
            
            if [ "$http_code" -eq 200 ] || [ "$http_code" -eq 201 ]; then
              echo "✓ Successfully synced: $title"
              echo "$body"
            else
              echo "✗ Failed to sync: $title (HTTP $http_code)"
              echo "$body"
            fi
            
            echo "---"
          done

      - name: Summary
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          echo "Sync completed"
